### ISSUE TITLE
Error with Meteor 1.3-modules-beta.8

### ISSUE THREAD

**Issue by massimilianomarini** [kadira-samples/meteor-data-and-react#3]
I've updated to the last beta release (1.3-modules-beta.8) and this is the error I got when the app start and I visit the page.

```
=> Started proxy.                             
=> Started MongoDB.                           
=> Started your app.                          

=> App running at: http://localhost:3000/
E20160207-17:24:54.644(1) (webapp_server.js:716) Error running template: Error: Meteor code 
must always run within a Fiber. Try wrapping callbacks that you pass to non-Meteor libraries with Meteor.bindEnvironment.
    at Object.Meteor._nodeCodeMustBeInFiber (packages/meteor/dynamics_nodejs.js:9:1)
    at [object Object]._.extend.get (packages/meteor/dynamics_nodejs.js:21:1)
    at Object.Tracker.autorun (packages/kadira:flow-router-ssr/server/plugins/ssr_data.js:51:29)
    at [object Object].Blaze.View.autorun (packages/blaze/view.js:209:1)
    at [object Object].<anonymous> (packages/blaze/builtins.js:157:1)
    at fireCallbacks (packages/blaze/view.js:279:1)
    at Object.Tracker.nonreactive (packages/tracker/tracker.js:589:1)
    at packages/blaze/view.js:276:1
    at Object.Blaze._withCurrentView (packages/blaze/view.js:538:1)
    at Object.Blaze._fireCallbacks (packages/blaze/view.js:275:1)
```

**Comment by discdiver** [comment]
Try switching the routing package from the ssr version to kadira:flowrouter
and updating the client->configs->context.js  to

import {FlowRouter} from 'meteor/kadira:flow-router';

That fix from Arunoda took care of the issue for me in the mantra sample
blog app.

Have a great day,
Jeff

**Comment by massimilianomarini** [comment]
Thanks @discdiver :+1:
