### ISSUE TITLE
1.3-beta.11 Object [object Object] has no method 'setDeferScriptLoading'

### ISSUE THREAD

**Issue by TeemoWan** [kadira-samples/meteor-data-and-react#4]
/Users/wanli/.meteor/packages/meteor-tool/.1.1.13-beta.11.1y3dufx++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:267
                                           throw(ex);
                                                  ^
TypeError: Object [object Object] has no method 'setDeferScriptLoading'
    at meteorInstall.server.configs.ssr.js (server/configs/ssr.js:3:12)
    at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:202:1)
    at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1)
    at /Users/wanli/nodejs/meteor13/wenzi/.meteor/local/build/programs/server/app/app.js:1251:1
    at /Users/wanli/nodejs/meteor13/wenzi/.meteor/local/build/programs/server/boot.js:245:10
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/wanli/.meteor/packages/meteor-tool/.1.1.13-beta.11.1y3dufx++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
    at /Users/wanli/nodejs/meteor13/wenzi/.meteor/local/build/programs/server/boot.js:140:5

**Comment by TeemoWan** [comment]
import {FlowRouter} from 'meteor/kadira:flow-router-ssr';
