### ISSUE TITLE
1.3-beta.11 ReferenceError: document is not defined

### ISSUE THREAD

**Issue by TeemoWan** [kadira-samples/meteor-data-and-react#5]
/Users/wanli/.meteor/packages/meteor-tool/.1.1.13-beta.11.1y3dufx++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:267
                        throw(ex);
                              ^
ReferenceError: document is not defined
    at node_modules/domready/ready.js:13:1
    at fns (node_modules/domready/ready.js:6:1)
    at meteorInstall.node_modules.domready.ready.js (node_modules/domready/ready.js:10:1)
    at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:202:1)
    at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1)
    at meteorInstall.node_modules.react-mounter.dist.index.js (node_modules/react-mounter/dist/index.js:21:1)
    at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:202:1)
    at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:75:1)
    at meteorInstall.node_modules.react-mounter.index.js (node_modules/react-mounter/index.js:1:1)
    at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:202:1)
Exited with code: 8

**Comment by TeemoWan** [comment]
update react-mounter@1.1.0, OK
