### ISSUE TITLE
Why use react-mixin will cause SSR error?

### ISSUE THREAD

**Issue by nightire** [kadira-samples/meteor-data-and-react#7]
I'm following this repo step by step, reproduce it and integrate some stacks that we use daily. When I wrote PostList component as a stateless one, everything just works fine, until I change it to `class PostList extends React.Component` (with react-mixin), meteor will throw error as below:

```
W20160221-18:41:08.155(8)? (STDERR) Warning: propTypes was defined as an instance property on PostList. Use a static property to define propTypes instead.
W20160221-18:41:08.155(8)? (STDERR) Warning: contextTypes was defined as an instance property on PostList. Use a static property to define contextTypes instead.
W20160221-18:41:08.156(8)? (STDERR) Error when doing SSR. path:/: PostList.getChildContext(): childContextTypes must be defined in order to use getChildContext().
W20160221-18:41:08.157(8)? (STDERR) Invariant Violation: PostList.getChildContext(): childContextTypes must be defined in order to use getChildContext().
W20160221-18:41:08.157(8)? (STDERR)     at invariant (node_modules/fbjs/lib/invariant.js:39:1)
W20160221-18:41:08.157(8)? (STDERR)     at [object Object].ReactCompositeComponentMixin._processChildContext (node_modules/react/lib/ReactCompositeComponent.js:328:1)
W20160221-18:41:08.157(8)? (STDERR)     at [object Object].ReactCompositeComponentMixin.mountComponent (node_modules/react/lib/ReactCompositeComponent.js:225:1)
W20160221-18:41:08.157(8)? (STDERR)     at [object Object].wrapper [as mountComponent] (node_modules/react/lib/ReactPerf.js:66:1)
W20160221-18:41:08.157(8)? (STDERR)     at Object.ReactReconciler.mountComponent (node_modules/react/lib/ReactReconciler.js:37:1)
W20160221-18:41:08.157(8)? (STDERR)     at [object Object].ReactCompositeComponentMixin.mountComponent (node_modules/react/lib/ReactCompositeComponent.js:225:1)
W20160221-18:41:08.157(8)? (STDERR)     at [object Object].wrapper [as mountComponent] (node_modules/react/lib/ReactPerf.js:66:1)
W20160221-18:41:08.157(8)? (STDERR)     at Object.ReactReconciler.mountComponent (node_modules/react/lib/ReactReconciler.js:37:1)
W20160221-18:41:08.157(8)? (STDERR)     at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (node_modules/react/lib/ReactMultiChild.js:241:1)
W20160221-18:41:08.157(8)? (STDERR)     at ReactDOMComponent.Mixin._createContentMarkup (node_modules/react/lib/ReactDOMComponent.js:591:1)
```

I use class form because I need mixins support, I installed react-mixin through NPM and add `reactMixin(PostList.prototype, SomeMixin)`, this specific line will cause the above errors.

Currently I don't know how to get around this issue, can you give me some ideas? Thanks in advance.

**Comment by nightire** [comment]
BTW, use `React.createClass` with `mixins` property will work either with ssr.

But if I change to `flow-router` without ssr support, `React.createClass` will work with mixins and class forms still can't work in browser.
